### ISSUE TITLE
RM-3 Create Intro

### ISSUE THREAD

**Issue by Sasha123456789987654321** [Sasha123456789987654321/homepage#10]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо

**Comment by spamreceiver234** [comment]
Юзанем рандомне резюме з ваших вот інтернетів 
https://resumegenius.com/resume-samples/financial-analyst-resume#text-format

Detail-oriented Financial Analyst with 6+ years of experience developing and presenting informed analysis to guide executive-level decisions. Possesses an M.S. in Accounting and CFA certified. Excited to leverage my extensive financial expertise in support of the team at Silver Management.
