### ISSUE TITLE
RM-6 Make additional information blocks

### ISSUE THREAD

**Issue by Sasha123456789987654321** [Sasha123456789987654321/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by spamreceiver234** [comment]
SKILLS

Problem Solving, Strategic Thinking, Performance Optimization, Risk Management, Leadership, Time Management, Critical Thinking, Adaptability, Collaboration

FINANCIAL ANALYST
Blackburn Inc., Pittsburgh, PA  / February 2017 – Present

Streamlined analysis of financial data, increasing accuracy of our forecasted revenue projections by 9%.
Prepare weekly reports and lead presentations to brief staff on financial outlook.
Monitor investments and provide recommendations based on current market trends.
Increased revenue by an average of 7% annually through an optimized investment strategy.
Develop onboarding materials and oversee training of 15 new employees each year.
FINANCE INTERN
Stuart and Son’s, Philadelphia, PA  / October 2016 – February 2017

Assisted in the development of a new risk assessment strategy, reducing losses by an average of 12%.
Compiled reports to inform management about the company’s financial outlook.
Developed highly accurate analysis of competitor market share.
Produced reports detailing the impact of debt financing on the company’s net income.
