### ISSUE TITLE
RM-5 Make a timeline

### ISSUE THREAD

**Issue by Sasha123456789987654321** [Sasha123456789987654321/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by spamreceiver234** [comment]
EDUCATION

M.S. / Accounting
University of Pennsylvania
2014 – 2016

B.S. / Accounting
Pennsylvania State University
2010 – 2014

Chartered Financial Analyst (CFA)
2015 – 2016
